export const vehicleData = [
  {
    title: "Saarthi Star",
    route: "vehicle/saarthi-star",
    image: "1.jpg",
    tableHeader: [
      "Motor",
      "Brake System Front / Rear",
      "Vehicle Body Material",
      "Passenger",
      "Controller",
      "Rim Front / Rear",
      "Battery",
      "Dimensions",
      "Wheel Base",
      "Charge Time",
      "Maximum Speed",
      "Maximum Load",
      "Charger",
    ],
    tableData: [
      "3000 Watts AC Motor",
      "Both Disk Brake",
      "MS Steel",
      "1+4 , 1+3 Both Available",
      "3000 watts",
      "All Alloy",
      "135 AH 60V LITHIUM",
      "2600X1300X1750 (mm)",
      "1980(mm)",
      "405 Hours",
      "50 km/h",
      "350kg",
      "30 Amp",
    ],
    showCaseImg: ["1.jpg", "saarthi_star_2.jpg", "saarthi_star_3.jpg"],
  },
  {
    title: "Saarthi Plus",
    route: "vehicle/saarthi-plus",
    image: "2.jpg",
    tableHeader: [
      "Motor",
      "Controller",
      "Differential",
      "Length",
      "Width",
      "Height",
      "Roof",
      "Wind Screen Glass",
      "Shocker",
    ],
    tableData: [
      "1000 Watts",
      "50 Amp 24 Tubes",
      "33 inch",
      "2730mm",
      "980mm",
      "1725mm",
      "Iron With Carrier",
      "With Motor & Wiper",
      "43mm",
    ],
    showCaseImg: ["2.jpg", "saarthi_plus_2.jpg"],
  },
  {
    title: "Saarthi DLX",
    route: "vehicle/saarthi-dlx",
    image: "3.jpg",
    tableHeader: [
      "Motor",
      "Controller",
      "Differential",
      "Length",
      "Width",
      "Height",
      "Roof",
      "Wind Screen Glass",
      "Shocker",
    ],
    tableData: [
      "1000 Watts",
      "50 Amp 24 Tubes",
      "33 inch",
      "2730mm",
      "980mm",
      "1725mm",
      "Iron With Carrier",
      "With Motor & Wiper",
      "43mm",
    ],
    showCaseImg: ["3.jpg", "saarthi_dlx_2.jpg"],
  },
  {
    title: "Saarthi Shevak E-Auto",
    route: "vehicle/saarthi-e-auto",
    image: "4.jpg",
    tableHeader: [
      "Motor",
      "Controller",
      "Brake System Front / Rear",
      "Vehicle Body Material",
      "Passenger",
      "Controller",
      "Rim Front / Rear",
      "Battery",
      "Dimenstions",
      "Wheel Base",
      "Charge Time",
      "Maximum Speed",
      "Maximum Load",
      "Charger",
    ],
    tableData: [
      "3000 Watts AC Motor",
      "Both Disk Brake",
      "MS Steel",
      "1+4 , 1+3 Both Available",
      "3000 Watts",
      "All Alloy",
      "135 AH 60V LITHIUM",
      "2600X1300X1750 (mm)",
      "1980 (mm)",
      "4-5 Hours",
      "50 km/h",
      "350 kg",
      "30 Amp",
    ],
    showCaseImg: [
      "4.jpg",
      "saarthi_shavak_e_auto_2.jpg",
      "saarthi_shavak_e_auto_3.jpg",
    ],
  },
  {
    title: "Saarthi Shevak Cargo L-5",
    route: "vehicle/saarthi-cargo-l5",
    image: "5.jpg",
    tableHeader: "",
    comingSoon: "coming_soon_icon.png",
    showCaseImg: [
      "5.jpg",
      "saarthi_shavak_cargo_l5_2.jpg",
      "saarthi_shavak_cargo_l5_3.jpg",
    ],
  },
  {
    title: "Saarthi Shaktiman",
    route: "vehicle/saarthi-shaktiman",
    image: "saarthi_shaktiman.jpg",
    tableHeader: [
      "Motor",
      "Controller",
      "Differential",
      "Length",
      "Width",
      "Height",
      "Wind Screen Glass",
      "Shocker",
    ],
    tableData: [
      "1370 / 400 Watts",
      "24 Tube",
      "33 inch",
      "2720mm",
      "940mm",
      "1690mm",
      "With Motor & Wiper",
      "43mm",
    ],
    showCaseImg: ["saarthi_shaktiman.jpg", "saarthi_shaktiman_2.jpg"],
  },
  {
    title: "Saarthi E-CAB",
    route: "vehicle/saarthi-e-cab",
    image: "6.jpg",
    tableHeader: [
      "Motor",
      "Controller",
      "Differential",
      "Length",
      "Width",
      "Height",
      "Roof",
      "Wind Screen Glass",
      "Shocker",
    ],
    tableData: [
      "1000 Watts",
      "50 Amp 24 Tubes",
      "35 inch",
      "2750 mm",
      "970 mm",
      "1750 mm",
      "Iron",
      "With Motor & Wiper",
      "43mm",
    ],
    showCaseImg: ["6.jpg", "saarthi_e_cab_2.jpg"],
  },
];
